### ISSUE TITLE
WALBlockDeviceChannel prevent dirty data

### ISSUE THREAD

**Issue by superhx** [AutoMQ/automq-for-kafka#453]
If the `src` data is less than alignSize, and there are valid historical data exactly between `src end` and alignSize, it could result in erroneous overwriting of old data.

![image](https://github.com/AutoMQ/automq-for-kafka/assets/5719209/7834722f-343f-4e82-b6f2-7c47a8e238ba)

**Comment by Chillax-0v0** [comment]
During recovery, we will check the `recoverStartOffset` (logic offset we try to recover) and `recordBodyOffset` (from the header we read from the disk). So any records whose offset mismatches will be dropped.
![image](https://github.com/AutoMQ/automq-for-kafka/assets/78631860/3d2d81af-1779-4096-8928-d4b0221743ba)
