### ISSUE TITLE
Broker hang on controlled shutdown

### ISSUE THREAD

**Issue by SCNieh** [AutoMQ/automq-for-kafka#462]
Controller logs:
![image](https://github.com/AutoMQ/automq-for-kafka/assets/20128924/3452c2cf-42b2-4ed3-895e-277529acbb9c)

Broker logs:
![image](https://github.com/AutoMQ/automq-for-kafka/assets/20128924/162b4905-5111-4b38-9b11-564bbe48daac)

**Comment by superhx** [comment]
The stream close workflow:
1. fence future write
2. await pending write
3. await upload wal cache to s3
4. close the stream

Potential buggy code:
1. Thread1-Stream1 - invoke forceUpload and the inflightWALUploadTasks is empty
2. Thread2-Stream2 - invoke forceUpload and the inflightWALUploadTasks is empty
3. Thread2-Stream2 - archive the cache
4. Thread1-Stream1 - archive the empty cache cause of step 3 already archive
5. Thread1-Stream1 - complete force upload
6. Thread2-Stream2 - uploadDeltaWAL and put task to inflightWALUploadTasks
7. Thread1-Stream1 - close stream
8. uploadDeltaWAL try commit stream1 + stream2 data to controller, but stream1 is already closed.
![image](https://github.com/AutoMQ/automq-for-kafka/assets/5719209/3cab455d-3f76-4b6a-8102-5245e4a61f0b)
