### ISSUE TITLE
Metrics mismatch: the count of wal.append is 5x larger than stream.append

### ISSUE THREAD

**Issue by daniel-y** [AutoMQ/automq-for-kafka#830]
## S3Stream Append
<img width="831" alt="image" src="https://github.com/AutoMQ/automq-for-kafka/assets/130526409/d41db5b2-7346-4f49-93b6-e8df05cb350f">

## WAL Append
<img width="854" alt="image" src="https://github.com/AutoMQ/automq-for-kafka/assets/130526409/5c04c586-509a-48b1-8e43-a386341b2a61">

**Comment by ShadowySpirits** [comment]
We should
